include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**.g.dart"
    - "**.freezed.dart"
  errors:
    invalid_annotation_target: ignore
    invalid_use_of_protected_member: error
    # missing_return: error
    # must_be_immutable: error
    # must_call_super: error