name: repostar
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  auto_route: ^3.2.4
  cached_network_image: ^3.2.0
  dartz: ^0.10.1
  dio: ^4.0.6
  flash: ^2.0.3+2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.3
  flutter_secure_storage: ^5.0.2
  freezed_annotation: ^2.0.1
  hooks_riverpod: ^2.0.0-dev.5
  json_annotation: ^4.5.0
  material_design_icons_flutter: ^5.0.6595
  oauth2: ^2.0.0
  path: ^1.8.1
  path_provider: ^2.0.9
  sembast: ^3.2.0
  shimmer: ^2.0.0
  webview_flutter: ^3.0.2

dev_dependencies: 
  auto_route_generator: ^3.2.3
  build_runner: ^2.1.10
  freezed: ^2.0.2
  json_serializable: ^6.2.0
  lint: ^1.8.2

flutter:
  uses-material-design: true